@startuml
title Add New Employee - Use Case Diagram

left to right direction

actor Official

rectangle SERVER{
    Official -- (Add Employee)
    (Add Employee) .> (Login) : <<include>>
    (Add Employee) ..> (Check Mansion) : <<include>>
    (Check Mansion) .> (Check Fiscal Code) : <<include>>
    (Check Mansion) <.. (Error): <<extends>>
    (Check Fiscal Code) <.. (Error) : <<extends>>
    (Error) ..> (Send Warning Response) : <<include>>
}
@enduml