@startuml
title Add New Employee - Use Case Diagram

left to right direction

actor Administrator
actor Director
actor Official

rectangle SERVER{
    Director -- (Add Employee)
    Administrator -- (Add Employee)
    Official -- (Add Employee)
    (Add Employee) ..> (Check Fiscal Code) : <<include>>
    (Add Employee) ..> (Check Mansion) : <<include>>
    (Add Employee) ..> (Login) : <<include>>
    (Login) <.. (Error) : <<extends>>
    (Check Mansion) <.. (Error): <<extends>>
    (Check Fiscal Code) <.. (Error) : <<extends>>
    (Error) ..> (Send Warning Response) : <<include>>
}
@enduml