@startuml
title Use Case Diagram

top to bottom direction

actor Administrator
actor Official
actor Director


rectangle  SERVER {
    Administrator -- (Employee Management)
    Director -- (Employee Management)
    Official -- (Employee Management)
    (Employee Management) --> (Update Employee) : <<include>>
    (Employee Management) --> (Add Employee) : <<include>>
    Director -- (Research)

    Administrator -- (Research)
    (Add Employee) ..> (Login) : <<include>>
    (Add Employee) ..> (Check FiscalCode) : <<include>>
    (Update Employee) ..> (Login) : <<include>>
    (Update Employee) ..> (Check FiscalCode) : <<include>>
    (Research) ..> (Login) : <<include>>
    (Research) ..> (Check Mansion) : <<include>>
}
@enduml