@startuml
title Use Case Diagram

top to bottom direction

actor Administrator
actor Official
actor Director


rectangle  SERVER {
    Official -- (Add Employee)
    Official -- (Update Employee)
    Director -- (Research)
    Administrator -- (Research)
    (Add Employee) ..> (Login) : <<include>>
    (Add Employee) .left.> (Check FiscalCode) : <<include>>
    (Update Employee) ..> (Login) : <<include>>
    (Update Employee) .right.> (Check FiscalCode) : <<include>>
    (Research) ..> (Login) : <<include>>
    (Research) .> (Check Mansion) : <<include>>
}
@enduml