@startuml
title Use Case Diagram

left to right direction

actor Logged_Client
actor Not_Registered_User
actor Admin


rectangle  Winehouse {

    Not_Registered_User -right- (Registration)
    Not_Registered_User -up- (Search Wine)

    Logged_Client -- (Search Wine)
    Logged_Client -- (Ask Notification)
    Logged_Client -- (Make Purchase)

    Admin -- (Refill Bottles)
    Admin -- (Ship Order)

    (Search Wine) <.up. (Ask Notification) : <<include>>
    (Search Wine) <.up. (Make Purchase) : <<include>>
}
@enduml