@startuml
title Use Case Diagram

left to right direction

actor Admin
actor Logged_Client
actor Not_Registered_User

rectangle  Winehouse {
    Logged_Client -- (Make Purchase)
    Logged_Client -- (Ask Notification)
    Logged_Client -- (Search Wine)

    Not_Registered_User -- (Registration)
    Not_Registered_User -- (Search Wine)

    Admin -- (Refill Bottles)
    Admin -- (Ship Order)

    (Search Wine) <.left. (Make Purchase) : <<include>>
    (Search Wine) <.down. (Ask Notification) : <<include>>
}
@enduml